### ISSUE TITLE
Light mode wallpaper

### ISSUE THREAD

**Issue by azdanov** [endeavouros-team/endeavouros-theming#10]
Hey!

I really like the [backgrounds/endeavouros-wallpaper.png](https://github.com/endeavouros-team/endeavouros-theming/blob/master/backgrounds/endeavouros-wallpaper.png) wallpaper.

Would it be possible to make similar, but for a light mode? I have an auto light/dark mode switcher and like to use light theme during the day for all my apps.

The image could be very similar, but instead of dark night and the planet, there could be blue sky and sun/moon or can keep the planet, just make it as if during the day?

Something similar to these 2, (without ARM text of course)
![image](https://github.com/user-attachments/assets/3b52c841-6505-454f-a49d-6881f0472aef)

**Comment by killajoe** [comment]
hi the implementation is there, in case the person creating the wallpaper for a release is providing light dark mode pictures. These are basically users contributing, we do not have a dedicated designer in the team.

https://github.com/endeavouros-team/endeavouros-DE-fixes/tree/main/gnome

it is here:
https://github.com/endeavouros-team/PKGBUILDS/blob/master/eos-settings-gnome/99_endeavouros-gnome.gschema.override

/usr/share/glib-2.0/schemas/99_endeavouros-gnome.gschema.override

https://github.com/endeavouros-team/PKGBUILDS/blob/master/eos-settings-gnome/endeavouros.xml

/usr/share/glib-2.0/schemas/98_endeavouros-gnome-console.gschema.override

You can see this time there is the same picture used for both modes simply because there is no dark version. 
take this package:

https://github.com/killajoe/eos-settings-gnome/releases/download/2.2/eos-settings-gnome-2.2-1-any.pkg.tar.zst

install with ` sudo pacman -U eos-settings-gnome-2.2-1-any.pkg.tar.zst`

and place a dark version here:
/usr/share/endeavouros/backgrounds/endeavouros-wallpaper-dark.png

**Comment by killajoe** [comment]
![endeavouros-wallpaper-dark](https://github.com/user-attachments/assets/aaa7c63f-1874-4f6e-b8ed-cfc04f9d1197)
something like this .. i am not a designer only used gimp to make it darker.

**Comment by UncleSpellbinder** [comment]
> Hey!
> 
> I really like the [backgrounds/endeavouros-wallpaper.png](https://github.com/endeavouros-team/endeavouros-theming/blob/master/backgrounds/endeavouros-wallpaper.png) wallpaper.
> 
> Would it be possible to make similar, but for a light mode? I have an auto light/dark mode switcher and like to use light theme during the day for all my apps.
> 
> The image could be very similar, but instead of dark night and the planet, there could be blue sky and sun/moon or can keep the planet, just make it as if during the day?
> 
> Something similar to these 2, (without ARM text of course) ![image](https://private-user-images.githubusercontent.com/6123841/384674698-3b52c841-6505-454f-a49d-6881f0472aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjQ0MDcsIm5iZiI6MTczMTQyNDEwNywicGF0aCI6Ii82MTIzODQxLzM4NDY3NDY5OC0zYjUyYzg0MS02NTA1LTQ1NGYtYTQ5ZC02ODgxZjA0NzJhZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMTUwODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFiNzNjMTk2YmM5NzkzMTA2ZTZlOTgyMjk1ZGE0NWZlMTVhODI5N2ZiOWUzYjFhODg1OTY0YjE5MDA1NzZiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fFreOYqz7n1xJYKecua8Aun-V0STHWEd5SK7YxGB4fs)

I don't know that I could use that exact image again as the steps I used to create it were deleted once the wallpaper was accepted by the EOS devs for use as the 5th year anniversary ISO wallpaper. If you're looking for general EOS rocket launch dark/light wallpaper, I could attempt creating something soon.
